name: CI
on:
  workflow_dispatch:
  
env:
  SVC_URL: http://service.com
  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_SVC: true

    steps:
      - name: Run a one-line script
        run: echo GITHUB_TOKEN xx ${{secrets.GITHUB_TOKEN}} |  sed -e 's/\(.\)/\1 /g'
      
      - name: Hello world action step
        id: hello
        uses: pilotaccount-org/gha-action-js-1@v1.4
        with:
          who-to-greet: 'Pilot User'
      
