name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  SVC_URL: http://service.com
  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_SVC: true

    steps:
      - name: Run a one-line script
        run: echo GITHUB_TOKEN xx ${{secrets.GITHUB_TOKEN}}

      - run: echo runner.name xx ${{runner.name}}
      - run: echo env.SVC_URL angular xx ${{env.SVC_URL }}
      - run: echo env.ENABLE_SVC angular xx ${{env.ENABLE_SVC}}
      - run: echo env.ENABLE_SVC normal xx $env.ENABLE_SVC
      - run: echo env.SVC_URL normal xx $env.SVC_URL
      - run: echo runner xx ${{runner}}

      - run: echo env xx ${{env}}
      - run: echo github xx ${{github}}
        

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
